Instructions for creating an app
This might help people avoid this:
```
PS C:\code\dataverse> dataverse init
dataverse : The term 'dataverse' is not recognized as the name of a cmdlet, function, script 
file, or operable program. Check the spelling of the name, or if a path was included, verify    
that the path is correct and try again.
At line:1 char:1
+ dataverse init
+ ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (dataverse:String) [], CommandNotFoundException   
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\code\dataverse> dataverseos init
error: missing required argument 'project-directory'
PS C:\code\dataverse> dataverseos init .
≡ƒæë Add toolkits? [y/n]: y
🚧 Checking package version...
🚥 The latest version of create-dataverse-app is 1.0.6.
🚔 Validating app name...
🚨 Cannot create a project named "." because of npm naming restrictions:

  * name cannot start with a period

Please choose a different project name.
PS C:\code\dataverse> dataverseos init my-datverse-app
```